---
# Replication Controller for springapp
apiVersion: v1
kind: Deployment 
metadata:
  name: spring-boot-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: 10.171.14.84:8086/repository/hello-world-java:latest
        name: springboot
        ports:
        - containerPort: 8080  

---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
